### ISSUE TITLE
Elixir nodes

### ISSUE THREAD

**Issue by pkoppstein** [duff/exeque#1]
Have you thought about adapting the library to make it "node-oriented" rather than process-oriented?

For example, suppose we have 4 Elixir nodes, and that we want to distribute the work in the queue to at most one "worker" at each node.

If not, any pointers would be appreciated.  Thanks.

**Comment by duff** [comment]
@pkoppstein I'm not sure!  I'm pretty new to Elixir, but I'd love to see what you might come up with a fork. :)
